#!/usr/bin/env bash

# desktop: 10.0.0.2     laptop: 10.0.0.3    rairden.us points to my desktop
copyDir() {
    COPYDIR=$(pwd)
    cd ..
    output=$(rsync -avh"$n" --stats "$1":"$COPYDIR" .)
    echo "$output"
    file=$HOME/.cache/tmp2.log
    echo "$output" > "$file"
    echo -e "\nYou ran the command:"
    echo -e "rsync -avh$n --stats $1:$COPYDIR .\n"

    transfer=$(perl -wne '/received:?\s(\d*.\d*\w)/i and print $1' < "$file")
    echo "You transferred a total of:  $transfer"

#    pcregrep -M "received:\s(\d*\S\w$)"

#    regex="received:\s(\d*\S\w$)"
#    [[ $output =~ $regex ]]
#    echo "${BASH_REMATCH[0]}"
#    echo "${BASH_REMATCH[1]}"

    # rsync -avh --stats 10.0.0.111:~/Documents .
    # rsync -avh --stats rairden.us:/home/erik/Documents .
}

n=$1
myip=$(ip -4 addr)

if [[ $myip =~ 10.0.0.3 ]]; then
    copyDir "10.0.0.2" "$n"
    exit
fi

copyDir "rairden.us" "$n"
