#!/usr/bin/env bash

# desktop: 10.0.0.2     laptop: 10.0.0.3    rairden.us points to my desktop
copyCollegeDir() {
    src=$HOME/externalDrives/storage/College
    dest=$HOME/PC
    output=$(rsync -avh"$2" --stats "$1":"$src" "$dest")
    echo -e "\n       Run cmd: rsync -avh$2 --stats $1:$src $dest"
    createdFiles=$(echo "$output" | pcregrep -o1 "Number of created files:\s(.*)")
    transferSize=$(echo "$output" | pcregrep -o1 "Total transferred file size:\s(.*)")

    echo "     New files: $createdFiles"
    echo "Transfer total: $transferSize"
}

flag=$1
myip=$(ip -4 addr)

if [[ $myip =~ 10\.0\.0\.3 ]]; then
    copyCollegeDir "10.0.0.2" "$flag"
    exit
fi

copyCollegeDir "rairden.us" "$flag"
