#!/bin/bash

# backup my files to two locations

readonly root=/run/media/erik/storage
dst1=/run/media/erik/storage/temp
dst2="$HOME/scratch/backup"

backup() {
	dst=$1
	[ -d "$dst" ] || return 1

	rsync -a --info=progress2,del --del ~/.dotfiles "$dst"
	rsync -a --info=progress2,del --del ~/.scripts "$dst"
	rsync -a --info=progress2,del --del ~/IdeaProjects "$dst"
	rsync -a --info=progress2,del --del ~/PycharmProjects "$dst"
	rsync -a --info=progress2,del --del ~/WebstormProjects "$dst"
	rsync -a --info=progress2,del --del ~/MyWebsites "$dst"
	rsync -a --info=progress2,del --del ~/Notes "$dst"
	rsync -a --info=progress2,del --del "$GOPATH"/src "$dst"
}

dst1=${dst1%/}
dst2=${dst2%/}

if [[ $dst1 = "$root" || $dst2 = "$root" ]]; then
	echo "Protecting against deleting the entire hard drive. Exiting."
	exit 1
fi

backup "$dst1"
backup "$dst2"
