#!/usr/bin/env bash

# desktop: 10.0.0.2     laptop: 10.0.0.3    rairden.us points to my desktop
copyCollegeDir() {
    SRC=$HOME/externalDrives/storage/College
    DEST=$HOME/PC
    rsync -avh"$n" --stats "$1":"$SRC" "$DEST"
    echo "rsync -avh"$n" --stats "$1":"$SRC" "$DEST""
    echo "ddd"
    # rsync -avh --stats 10.0.0.2:~/Documents .
    # rsync -avh --stats rairden.us:/home/erik/Documents .
}

n=$1
MYIP=$(ip -4 addr)

if [[ $MYIP =~ 10.0.0.3 ]]; then
    copyDir "10.0.0.2" "$n"
    exit
fi

copyDir "rairden.us" "$n"
