#!/bin/bash

# desktop: 10.0.0.2     laptop: 10.0.0.3    rairden.us points to my desktop
copyDir() {
    copyDir=$(pwd)
    cd ..
    upOne=$(pwd)

    if [ "$2" == "rev" ]; then
        output=$(rsync -avh"$3" --stats "$copyDir" "$1":"$upOne")
        if [ "$3" == "n" ]; then
            echo -e "\n      (DRY RUN)"
        fi
        echo -e "       Run cmd: rsync -avh$3 --stats $copyDir $1:$copyDir"
        printSummary "$output"
        exit
    fi

    if [ "$2" == "n" ]; then
        echo -e "\n      (DRY RUN)"
    fi
    output=$(rsync -avh"$2" --stats "$1":"$copyDir" .)
    echo -e "       Run cmd: rsync -avh$2 --stats $1:$copyDir ."
    printSummary "$output"
}

printSummary() {
    createdFiles=$(echo "$1" | pcregrep -o1 "Number of created files:\s(.*)")
    transferSize=$(echo "$1" | pcregrep -o1 "Total transferred file size:\s(.*)")
    echo "     New files: $createdFiles"
    echo "Transfer total: $transferSize"
}

rev=$1
flag=$2
myIP=$(ip -4 addr)

if [[ $myIP =~ 10\.0\.0\.3 ]]; then
    copyDir "10.0.0.2" "$rev" "$flag"
    exit
fi

copyDir "rairden.us" "$rev" "$flag"
