#!/bin/bash

# Showing examples of how to use this script:
# a=$(ps aux | rg java) 
# b=$(ps aux | rg java) 
# diffy $a $b

a=$1
b=$2
file=/home/$USER/.cache/tmp.patch

if [ "$#" = 0 ] || [ "$#" = 1 ]; then
    echo "Enter two or more arguments."
    exit 1
else
    diff -rup <(echo "$a") <(echo "$b") > "$file"
    colordiff -rup <(echo "$a") <(echo "$b")

    vim "$file"
fi
