#!/bin/bash

dir=$1

if [[ $# -eq 1 ]]; then
	path=$(realpath "$1")
	cd "$dir" || exit 1
	traceit du -sh "$path"
fi

PS41="\n\033[1;31m>>>\033[0m "

echo -e "${PS41}du -sh -- * | sort -hr"
du -sh -- * | sort -hr
