#!/bin/bash

if [ $# -eq 0 ]; then
	echo "Usage: ./$(basename "$0") search"
	exit
fi

search="$1"
find ! \( -path "*/.git" -prune \
		-o -path "*/venv" -prune \
		-o -path "*/.idea" -prune \) -type f | rg -i "/${search}[^/]*$"
