#!/bin/bash

repos="$HOME/repos"
mkdir -p "$repos"

usage() {
	script="./$(basename "$0")"

	cat <<-DOC
	Usage: $script url

	Clones a git repo. Makes one directory for each username (edit repos=).
	To automatically cd into the project directory, source this script (. $script url).

	To download many repos at once you could run:
        while read -r line; do $script \$line; done < in.txt

	This script requires pcregrep. Install with either:
        sudo apt-get install pcregrep
        sudo pacman -S pcre
DOC
}

isValidGitURL() {
	url=$1
	validURL="((git|ssh|http(s)?)|(git@[\w\.]+))(:(//)?)([\w\.@\:/\-~]+)(\.git)(/)?"	# https://regex101.com/r/h7Ql2c
	echo "$url" | grep -Pq "$validURL"
	return $?
}

requireBinary() {
	local binary=$1
	if ! command -v "$binary" &> /dev/null; then
		echo "Error: $binary is not installed."
		return 1
	fi
	return 0
}

requireBinary pcregrep || exit $?

if [ $# -eq 0 ]; then
	usage
	exit 1
fi

cd "$repos" || exit 1
url=$1

if ! isValidGitURL "$url"; then
	echo "Not a valid git repo URL."
	return 1 2>/dev/null	# safely exit if sourced
	exit 1
fi

regex="(https|git)(:\/\/|@)([^\/:]+)[\/:]([^\/:]+)\/(.+)(.git)*"	# https://regex101.com/r/FgBzpQ
aur="https://aur\.archlinux\.org/(.+)\.git"
relpath=

if [[ $url =~ $regex ]]; then
	site=$(echo "$url" | pcregrep -o3 "$regex")
	user=$(echo "$url" | pcregrep -o4 "$regex")
	repo=$(echo "$url" | pcregrep -o5 "$regex")
	repo="$(basename "$repo" .git)"
	relpath="$site/$user/$repo"
elif [[ $url =~ $aur ]]; then
	repo=$(echo "$url" | pcregrep -o1 "$aur")
	relpath=aur/"$repo"
else
	repo=$(basename "$url" .git)
	relpath=misc/"$repo"
fi

if git clone "$url" "$relpath"; then
	cd "$relpath" || return 1
fi
