#!/bin/bash

cd "$(git rev-parse --show-toplevel)" || exit 1

traceit tree .git/objects
traceit du -sh .git/objects

traceit bat .git/config
traceit git --no-pager branch -a
traceit bat .git/HEAD
traceit git fsck
