#!/bin/bash

# This script grabs your .gitignore templates from 'dir' depending on the programming language of your choice.
#
# How to use script:
#   0) Place gitignore template files in a folder 'dir'. Name the files to contain a keyword (gitignore-java).
#   1) Edit 'dir' to point to your gitignore templates folder
#   2) cd to a project folder
#   3) Run ./gitinit X       (replace X with a lang: go, java, c, python)
#          ./gitinit java

gitinit() {
	git init
    git add .
    git commit -m "Initial commit"
    git checkout -b dev
}

if [ $# -eq 0 ]; then
    gitinit
else
    dir=$HOME/.dotfiles/gitignore
    lang=$1
    myFiles=$(ls "$dir")

    for file in $myFiles; do
        if [[ ${file,,} =~ ${lang,,} ]]; then
            cp "$dir/$file" .gitignore
            gitinit
            echo
            echo -e "Copied file: $dir/$file"
            echo -e " Renamed to: .gitignore"
            exit
        fi
    done

    echo "Searching directory '$dir'."
    echo "Searching for '$1' found no files."
fi
