#!/bin/bash

start() {
    systemctl start sshd
    systemctl start fail2ban
    systemctl start mariadb
}

status() {
    systemctl status sshd
    systemctl status fail2ban
    systemctl status mariadb
    fail2ban-client status sshd
}

stop() {
    systemctl stop sshd
    systemctl stop fail2ban
    systemctl stop mariadb
}

