#!/bin/bash

# Using https://github.com/familyfriendlymikey/mpv-cut
# Hit 'a' a few times toggling to LIST mode.
# You create a .list file by hitting 'c' (CUT) twice in LIST mode.
# You can make 3 cut segments (6 markers) by hitting 'c' 6 times.
# Run this script to go through all .list files, and cut/concat them.

source "$HOME"/.config/mpv/scripts/mpv-cut/utils

shopt -s nullglob
listFiles=(*.list)
if [[ ${#listFiles[@]} -eq 0 ]]; then
	echo "No .list files found. Aborting."
	exit 1
fi

echo "Trimmed:"
totalSaved=0

for list in "${listFiles[@]}"; do
	vid="${list%.list}"
	ext="${vid##*.}"
	vid_noext="${vid%.*}"

	# Remove any old CUT_ files for this vid to avoid overwrites
	rm -f "CUT_"*

	output="${vid_noext}e.${ext}"	# vid1.mp4 -> vid1e.mp4
	make_cuts "$list" -c copy &>/dev/null
	concat "CUT" -c copy "$output" &>/dev/null

	origSize=$(stat -c %s "$vid")
	newSize=$(stat -c %s "$output")
	saved=$((origSize - newSize))
	totalSaved=$((totalSaved + saved))  # Keep running total

	savedSize=$(numfmt --to=iec-i --suffix=B --format="%.0f" $saved)

	kioclient5 move "$vid" trash:	# Move original file to trash
	kioclient5 move "$list" trash:	# Move .list file

	printf "%-15s %s\n" "$savedSize" "$vid"
done

rm -f CUT_*

totalTrimmed=$(numfmt --to=iec-i --suffix=B --format="%.0f" $totalSaved)
echo -e "\nTotal Trimmed: $totalTrimmed"
